/* Local input acceptance checks. Simulation is accelerated only in this test. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=(process.env.BASE_URL||'http://127.0.0.1:8765/').replace(/\/?$/,'/'),shots='artifacts/bowling';fs.mkdirSync(shots,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:768,height:1024},hasTouch:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'bowling/');await page.waitForFunction(()=>!document.getElementById('start').disabled);await page.evaluate(()=>{const G=BowlingCore.Game;BowlingCore.Game=class extends G{constructor(o){super(o);window.testGame=this;}step(dt,r){for(let i=0;i<10;i++)super.step(dt,r);}};});await page.click('#start');
async function pos(){const box=await page.locator('#game').boundingBox(),g=await page.evaluate(()=>({x:testGame.ball.x,y:testGame.ball.y})),scale=Math.min(box.width*.93/770,box.height/750),depth=1-.62*g.y/1450;return{x:box.x+box.width/2+g.x*scale*depth,y:box.y+box.height*.94-g.y/1450*box.height*.84};}
async function mouseSwipe(dx=0){const p=await pos();await page.mouse.move(p.x,p.y);await page.mouse.down();for(let i=1;i<=8;i++){await page.mouse.move(p.x+dx*i/8,p.y-i*16);await page.waitForTimeout(25);}await page.mouse.up();}
assert.equal(await page.locator('#go').count(),0);const p=await pos();await page.mouse.click(p.x,p.y);await page.mouse.click(p.x,p.y-30,{delay:120});await page.locator('#game').press('Space');assert.equal(await page.evaluate(()=>testGame.state),'aim');
await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+80,p.y,{steps:8});await page.mouse.up();assert.ok(await page.evaluate(()=>testGame.startX>70));assert.equal(await page.evaluate(()=>testGame.state),'aim');console.log('Tap, Space and horizontal dragging do not fire; horizontal dragging moves start');
await page.locator('#start-position').focus();await page.locator('#start-position').press('End');assert.equal(await page.evaluate(()=>testGame.startX),234);await mouseSwipe(65);await page.waitForFunction(()=>testGame.state!=='aim');await page.click('#pause');const frozen=await page.evaluate(()=>JSON.stringify([testGame.ball,testGame.card.frames]));await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>JSON.stringify([testGame.ball,testGame.card.frames])),frozen);await page.click('#resume');await page.waitForFunction(()=>testGame.card.frames[0].length===1);assert.equal(await page.evaluate(()=>testGame.card.frames[0][0]),0);assert.equal(await page.evaluate(()=>testGame.lastRoll.gutter),true);await page.screenshot({path:shots+'/gutter-tablet.png'});await page.waitForFunction(()=>testGame.state==='aim');assert.equal(await page.evaluate(()=>testGame.standing),10);console.log('Edge start and outward swipe gutter for 0; pause freezes physics and score');
await page.locator('#start-position').focus();await page.locator('#start-position').press('Home');for(let i=0;i<234;i++)await page.locator('#start-position').press('ArrowRight');assert.equal(await page.evaluate(()=>testGame.startX),0);
const cdp=await context.newCDPSession(page),touch=await pos();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touch.x,y:touch.y}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touch.x,y:touch.y-i*16}]});await page.waitForTimeout(25);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>testGame.state!=='aim');await page.waitForFunction(()=>testGame.card.index===1);assert.ok(await page.evaluate(()=>testGame.card.frames[0][1]>0&&testGame.card.frames[0][1]<10));await page.waitForFunction(()=>testGame.state==='aim');assert.equal(await page.evaluate(()=>testGame.standing),10);assert.equal(await page.evaluate(()=>testGame.score),await page.evaluate(()=>testGame.card.frames[0][1]));console.log('Real touch swipe hits pins; next frame resets rack and scores the open frame');
await page.screenshot({path:shots+'/play-tablet.png'});const start=await pos();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:start.x,y:start.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x,y:start.y-90}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await page.evaluate(()=>testGame.state),'aim');console.log('Cancelled touch gesture does not fire');
await page.click('#pause');await page.click('#quit');assert.equal(await page.evaluate(async()=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0)),0);await page.setViewportSize({width:390,height:844});await page.click('#start');await page.screenshot({path:shots+'/play-phone.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.click('#pause');await page.click('#quit');await page.click('#help-open');await page.screenshot({path:shots+'/help-phone.png'});assert.deepEqual(errors,[]);await browser.close();console.log('Bowl input acceptance PASS; unfinished games award no sticker');})().catch(e=>{console.error(e);process.exit(1);});
