const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{gamePage}=require('./game-page.cjs');
const base=(process.env.BASE_URL||'http://127.0.0.1:8768/allie/').replace(/\/?$/,'/'),out='artifacts/allie-redesign-v2/fullscreen';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1024,height:768},hasTouch:true}),page=await gamePage(context),shell=page.shell,errors=[];shell.on('pageerror',e=>errors.push(e.message));shell.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});shell.setDefaultTimeout(15000);
 async function toolbar(){for(const id of ['#allie-home','#allie-fullscreen']){const b=await shell.locator(id).boundingBox();assert.ok(b&&b.y>=0&&b.y+b.height<=65,'toolbar stays inside the viewport: '+id+' '+JSON.stringify(b));}const box=await shell.locator('#allie-game').boundingBox();assert.ok(box.y>=59,'game must stay below the toolbar');assert.equal(await shell.locator('#allie-game').count(),1);assert.equal(await page.locator('#allie-game').count(),0,'no nested hosts');}
 async function full(){await shell.waitForFunction(()=>document.fullscreenElement===document.documentElement);await toolbar();}
 async function home(){await shell.click('#allie-home');await shell.waitForURL(base);await page.waitForSelector('#games');await full();}
 for(const route of ['studio/','runner/','slice/','bowling/','piano/','drums/','stickers/','']){await page.goto(base+route);await toolbar();}assert.deepEqual(errors,[]);console.log('All eight direct URLs open one shell without duplicate game initialization');
 await shell.click('#allie-fullscreen');await full();await shell.evaluate(()=>window.hostMarker='persistent');
 for(const route of ['runner/','slice/','bowling/','piano/','drums/','studio/']){
  const href=new URL(route,base).href;await page.locator('#games a').filter({has:page.locator('h2')}).evaluateAll((links,href)=>links.find(a=>a.href===href).click(),href);await shell.waitForURL(href);await full();assert.equal(await shell.evaluate(()=>window.hostMarker),'persistent');
  if(route==='studio/'){await page.waitForFunction(()=>document.querySelectorAll('#gallery .gallery-card').length===10&&!document.querySelector('#tools button').disabled);await page.click('#open-gallery');await full();await page.locator('#paper-drawer [data-close]').click();await page.click('#tools button[data-tool=pen]');const b=await page.locator('#layer-bottom').boundingBox();await shell.mouse.move(b.x+20,b.y+20);await shell.mouse.down();await shell.mouse.move(b.x+80,b.y+60,{steps:5});await shell.mouse.up();await shell.click('#allie-home');await page.waitForSelector('#leave-dialog[open]');await full();await page.click('#leave-yes');await shell.waitForURL(base);await page.waitForSelector('#games');await full();}
  else{await page.waitForFunction(()=>!document.getElementById('start').disabled);await page.click('#start');await page.waitForSelector('#play:not([hidden])');await full();await page.click('#pause');await page.waitForSelector('#pause-dialog[open]');await full();await shell.click('#allie-fullscreen');await shell.waitForFunction(()=>!document.fullscreenElement);await shell.click('#allie-fullscreen');await full();await home();}
 }
 console.log('Fullscreen survives homepage -> all six games -> play/pause/dialog -> homepage; studio saves before Home');
 await shell.evaluate(()=>AllieScreen.navigate('runner/'));await shell.waitForURL(base+'runner/');await page.waitForSelector('#start');await home();await shell.evaluate(()=>history.back());await shell.waitForURL(base+'runner/');await full();await shell.evaluate(()=>history.forward());await shell.waitForURL(base);await page.waitForSelector('#games');await full();console.log('Browser Back/Forward keeps the same fullscreen host');
 // Reward and Use navigate within the same fullscreen document.
 await page.locator('a[href$="slice/"]').first().click();await shell.waitForURL(base+'slice/');await page.waitForFunction(()=>!document.getElementById('start').disabled);await page.evaluate(()=>{const G=SliceCore.Game;SliceCore.Game=class extends G{constructor(o){super(o);window.testGame=this;}};});await page.click('#start');await page.waitForSelector('#play:not([hidden])');
 for(let i=0;i<20;i++){await page.evaluate(()=>{const g=testGame;g.objects=[];const o=g.spawn();Object.assign(o,{x:g.width/2,homeX:g.width/2,y:g.height/2,amplitude:0,vy:0});});await page.locator('#game').press('Enter');await page.waitForTimeout(180);}
 await page.waitForSelector('#reward:not([hidden])');await full();await page.click('#open-chest');await page.waitForSelector('#reward-actions:not([hidden])');await full();await page.click('#use-sticker');await shell.waitForURL(/studio\/\?sticker=/);await page.waitForFunction(()=>document.body.dataset.tool==='sticker'&&!document.querySelector('#tools button').disabled);await full();await home();console.log('Reward, sticker Use and the drawing page keep fullscreen');
 for(const size of [{width:768,height:1024},{width:1024,height:768},{width:390,height:844},{width:844,height:390}]){
  await shell.click('#allie-fullscreen');await shell.waitForFunction(()=>!document.fullscreenElement);await shell.setViewportSize(size);await shell.click('#allie-fullscreen');await full();
  for(const route of ['runner/','slice/','bowling/','piano/','drums/','studio/']){await shell.evaluate(route=>AllieScreen.navigate(route),route);await shell.waitForURL(base+route);await page.waitForFunction(()=>document.readyState==='complete');await full();if(route==='studio/')await page.waitForFunction(()=>!document.querySelector('#tools button').disabled);else{await page.waitForFunction(()=>!document.getElementById('start').disabled);await page.click('#start');const rhythm=route==='piano/'||route==='drums/';await page.waitForSelector(rhythm?'.note-field':'#game');const field=await page.locator(rhythm?'.note-field':'#game').boundingBox();assert.ok(field.width>=290&&field.height>=105,route+' field '+JSON.stringify(field));if(route!=='slice/'){const c=await page.locator(rhythm?'#instrument':'.controls').boundingBox();assert.ok(c.y+c.height<=size.height+2,route+' controls clipped '+JSON.stringify(c));}}
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow');await toolbar();if(size.width===390||size.width===844)await shell.screenshot({path:out+'/'+route.replace('/','')+'-'+size.width+'.png'});
  }
 }
 console.log('Persistent controls and game fields fit four phone/tablet sizes');
 await shell.click('#allie-fullscreen');await shell.waitForFunction(()=>!document.fullscreenElement);await shell.evaluate(()=>{document.documentElement.requestFullscreen=undefined;document.documentElement.webkitRequestFullscreen=undefined;});await shell.click('#allie-fullscreen');assert.ok(await shell.locator('#allie-screen-notice').isVisible());await toolbar();console.log('Exit and unsupported-browser fallback work from a game');assert.deepEqual(errors,[]);await browser.close();console.log('Fullscreen acceptance PASS');
})().catch(e=>{console.error(e);process.exit(1);});
