const {gamePage}=require('./game-page.cjs');
/* Focused acceptance for the 2026-10 picture-book refresh. Fixture rewards use
 * the production transaction API in an isolated browser context. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
const base=(process.env.BASE_URL||'http://127.0.0.1:8768/allie/').replace(/\/?$/,'/'),out=process.env.SCREENSHOTS||'artifacts/allie-redesign-v2/polish';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1180,height:820}}),page=await gamePage(context),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
const count=()=>page.evaluate(async()=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0));
async function stateCount(n){await page.waitForFunction(async n=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0)===n,n);await page.waitForFunction(()=>!document.querySelector('#tools button[data-tool=sticker]').disabled);}
await page.goto(base+'stickers/');await page.evaluate(async()=>{await Allie.ready;await Allie.reward('bowling:polish-one','bowling');await Allie.reward('bowling:polish-two','bowling');});await page.getByRole('link',{name:'Use',exact:true}).first().waitFor();
const use=page.getByRole('link',{name:'Use',exact:true}).first();await use.click();await page.waitForFunction(()=>document.body.dataset.tool==='sticker'&&document.getElementById('busy').hidden);await page.waitForTimeout(100);let box=await page.locator('#sticker-layer').boundingBox();await page.mouse.click(box.x+box.width*.3,box.y+box.height*.55);await stateCount(1);
await page.click('#undo');await stateCount(2);await page.waitForFunction(()=>!document.getElementById('redo').disabled);await page.click('#redo');await stateCount(1);assert.equal((await page.evaluate(async()=>Allie.getDraft(await Allie.lastDraft()))).placements.length,1);console.log('Use preselects the earned sticker; Undo refunds and Redo consumes the same copy');
await page.click('#undo');await stateCount(2);await page.click('#tools button[data-tool=pen]');box=await page.locator('#layer-bottom').boundingBox();await page.mouse.move(box.x+30,box.y+30);await page.mouse.down();await page.mouse.move(box.x+80,box.y+70,{steps:4});await page.mouse.up();assert.equal(await page.locator('#redo').isDisabled(),true);console.log('A new drawing stroke clears redo history');
await page.click('#brush-open');await page.click('#brush-size button:last-child');assert.equal(await page.locator('#brush-drawer').evaluate(d=>d.open),true);await page.click('#brush-material button:last-child');await page.locator('#brush-drawer [data-close]').last().click();await page.click('#open-gallery');assert.equal(await page.locator('#gallery .gallery-card').count(),10);await page.locator('#paper-drawer [data-close]').click();
await page.screenshot({path:out+'/draw.png'});
for(const size of [{width:768,height:1024},{width:1024,height:768},{width:390,height:844},{width:844,height:390}]){
 await page.setViewportSize(size);for(const route of ['','studio/','runner/','slice/','bowling/','stickers/']){await page.goto(base+route);await page.evaluate(()=>Allie.ready);await page.waitForTimeout(220);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow '+size.width);if(['runner/','slice/','bowling/'].includes(route)){await page.waitForFunction(()=>!document.getElementById('start').disabled);await page.click('#start');await page.locator('#game').waitFor({state:'visible'});const field=await page.locator('#game').boundingBox();assert.ok(field.height>=105&&field.width>=290,route+' field size');const bottom=route==='runner/'?await page.locator('.controls').boundingBox():route==='bowling/'?await page.locator('.controls').boundingBox():field;assert.ok(bottom.y+bottom.height<=size.height+2,route+' controls clipped '+size.width);if(route==='bowling/'){const bounds=await page.evaluate(()=>{const r=new BowlingArt.Renderer(Object.assign(document.createElement('canvas'),{getBoundingClientRect:()=>document.getElementById('game').getBoundingClientRect()})),g=new BowlingCore.Game(),p=r.ballPosition(g);return{top:p.y-p.r,bottom:p.y+p.r,height:r.height};});assert.ok(bounds.top>=0&&bounds.bottom<=bounds.height,'bowling ball clipped');}}
 if(size.width===1024)await page.screenshot({path:out+'/'+(route.replace('/','')||'home')+'-landscape.png'});
 }
}
console.log('All six screens fit four phone/tablet sizes; gameplay controls and bowling ball stay visible');assert.deepEqual(errors,[]);await context.close();await browser.close();console.log('Polish acceptance PASS');})().catch(e=>{console.error(e);process.exit(1);});
