const test=require('node:test'),assert=require('node:assert/strict'),C=require('../wwwroot/rhythm/core.js'),songs=require('../wwwroot/rhythm/songs.js'),shared=require('../wwwroot/shared/core.js');
test('20 historic-melody arrangements form playable complete charts',()=>{
  for(const mode of ['piano','drums']){assert.equal(songs[mode].length,10);assert.equal(new Set(songs[mode].map(s=>s.id)).size,10);for(const s of songs[mode]){const chart=C.chart(s,mode);assert.ok(chart.end>=38&&chart.end<=80,s.id+' length');assert.ok(chart.notes.length>=20);assert.ok(chart.melody.length>=20);assert.ok(chart.notes.every((n,i,a)=>n.time>=chart.lead&&n.time<chart.end&&(!i||n.time>=a[i-1].time)));assert.ok(chart.backing.every(n=>n.midi>=28&&n.duration>0));const game=new C.Game(chart);for(const n of chart.notes)assert.ok(game.hit(n.lane,n.time));assert.equal(game.score,chart.notes.length*100);game.advance(chart.end);assert.ok(game.eligible);assert.equal(game.misses,0);if(mode==='piano'){assert.ok(chart.notes.every(n=>C.keys[n.lane]===n.midi&&n.duration>=.7));assert.ok(chart.notes.every((n,i,a)=>!i||n.time-a[i-1].time>=.7));}else assert.ok(chart.notes.every(n=>n.lane===0||n.lane===1));}}
});
test('notation preserves rests, accidentals and note durations; rejects malformed data',()=>{const p=C.parse('C4:1 R:.5 F#4:.5 Bb4:2');assert.deepEqual(p.notes.map(n=>n.midi),[60,null,66,70]);assert.equal(p.beats,4);assert.equal(p.notes[2].beat,1.5);for(const s of ['C4:0','C4:-1','X4:1','C4:20','C4','C4:NaN'])assert.throws(()=>C.parse(s));assert.throws(()=>C.chart({bpm:76,notation:'C#4:1'},'piano'));});
test('wrong lane, early tapping and duplicate hits cannot consume the next note',()=>{const g=new C.Game(C.chart(songs.piano[0],'piano'));assert.equal(g.hit(0,1),null);assert.equal(g.hit(1,3),null);assert.equal(g.hit(0,3)?.points,100);assert.equal(g.hit(0,3),null);assert.equal(g.hits,1);assert.equal(g.notes[1].state,'pending');assert.equal(g.hit(0,2),null,'previous invalid time must not move game backwards');});
test('great/good windows, late misses and completion use a monotonic clock',()=>{const chart=C.chart(songs.piano[0],'piano'),g=new C.Game(chart);assert.equal(g.hit(0,3.25).label,'Good!');assert.equal(g.score,50);g.advance(4.2);assert.equal(g.notes[1].state,'miss');assert.equal(g.misses,1);assert.equal(g.hit(0,3),null);g.advance(1);assert.equal(g.elapsed,4.2);assert.equal(g.eligible,false);g.advance(chart.end);assert.equal(g.eligible,true);assert.equal(g.hit(0,chart.end),null);const empty=new C.Game(chart);empty.advance(chart.end);assert.equal(empty.eligible,false);assert.equal(empty.misses,chart.notes.length);});
test('two independent drum lanes can be hit at the same instant',()=>{const g=new C.Game(C.chart(songs.drums[0],'drums')),pair=g.notes.find(n=>g.notes.some(m=>m.id!==n.id&&m.time===n.time&&m.lane!==n.lane));g.advance(pair.time-.2);assert.ok(g.hit(0,pair.time));assert.ok(g.hit(1,pair.time));assert.equal(g.hits,2);assert.equal(g.hit(1,pair.time),null);});
test('rhythm records restrict scores and pending reward IDs to known songs and game',()=>{const r=C.records({last:'bad',best:{twinkle:100,mary:-1,london:1e10,bad:100},pending:[{id:'piano:1234567890-ab',song:'twinkle',score:100},{id:'drums:1234567890',song:'twinkle',score:100},{id:'piano:1234567890',song:'fake',score:100},{id:'piano:1234567890',song:'twinkle',score:0}]},songs.piano,'piano');assert.equal(r.last,'twinkle');assert.deepEqual(r.best,{twinkle:100});assert.equal(r.pending.length,1);assert.deepEqual(C.records(null,songs.drums,'drums'),{best:{},last:'jingle',pending:[]});});
test('both rhythm games share idempotent consumable sticker units',()=>{const state=shared.fresh();for(const game of ['piano','drums']){const id=game+':song-session';assert.equal(shared.claim(state,id,game,'unicorn').fresh,true);assert.equal(shared.claim(state,id,game,'penguin').fresh,false);}assert.equal(state.units.length,2);assert.equal(shared.counts(state).unicorn,2);assert.throws(()=>shared.claim(state,'piano:foo','drums','unicorn'));});
