const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),{gamePage}=require('./game-page.cjs');
const base=(process.env.BASE_URL||'http://127.0.0.1:8768/allie/').replace(/\/?$/,'/'),out='artifacts/music-implementation';fs.mkdirSync(out,{recursive:true});
async function capture(page){await page.evaluate(()=>{const G=RhythmCore.Game;RhythmCore.Game=class extends G{constructor(t){super(t);window.testGame=this;}};const timeline=RhythmAudio.prototype.timeline;RhythmAudio.prototype.timeline=function(...a){window.testAudio=this;return timeline.apply(this,a);};});}
async function fastSong(page){await page.evaluate(async()=>{const a=testAudio,g=testGame;a.virtual=a.now();a.now=()=>a.virtual;for(const n of g.notes){a.virtual=a.origin+n.time;document.querySelectorAll('.key')[n.lane].click();await new Promise(requestAnimationFrame);}a.virtual=a.origin+g.track.end+.01;await new Promise(requestAnimationFrame);});await page.waitForSelector('#result-dialog[open]');await page.waitForSelector('#reward .allie-reward a');}
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:768,height:1024},hasTouch:true}),page=await gamePage(context),errors=[];page.shell.on('pageerror',e=>errors.push(e.message));page.shell.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});page.shell.setDefaultTimeout(15000);await page.goto(base);await page.waitForFunction(()=>document.querySelectorAll('#games .game-card').length===6);assert.equal(await page.locator('#games h2').allTextContents().then(a=>a.join(',')),'Draw,Go!,Slice,Bowl,Piano,Drums');await page.shell.screenshot({path:out+'/home-six.png'});console.log('Homepage has six working game cards');
 for(const mode of ['piano','drums']){
  await page.goto(base+mode+'/');await capture(page);const beforeMode=await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length);assert.equal(await page.locator('.song-card').count(),10);await page.click('#listen');await page.waitForFunction(()=>testAudio.context?.state==='running');assert.equal(await page.locator('#listen').textContent(),'Stop');await page.waitForTimeout(3200);assert.ok(await page.evaluate(()=>testAudio.nodes.size>0),'listen schedules actual synthesized audio');
  const audible=await page.evaluate(async()=>{const a=testAudio,an=a.context.createAnalyser();an.fftSize=256;a.master.connect(an);await new Promise(r=>setTimeout(r,60));const samples=new Float32Array(256);an.getFloatTimeDomainData(samples);a.master.disconnect(an);return Math.max(...samples.map(Math.abs));});assert.ok(audible>.0001,'audio waveform must be nonzero');await page.click('#listen');assert.equal(await page.evaluate(()=>testAudio.nodes.size),0);assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),beforeMode,'Listen never awards');
  await page.click('#start');await page.waitForFunction(()=>testGame.elapsed>1);await page.locator('.key').last().click();assert.equal(await page.locator('#score').textContent(),'0','early input does not score');await page.waitForFunction(()=>testGame.elapsed>=2.97);if(mode==='piano'){await page.keyboard.down('a');await page.waitForTimeout(850);assert.equal(await page.evaluate(()=>testGame.hits),1,'holding one key is not repeated input');await page.keyboard.up('a');}else{const cdp=await context.newCDPSession(page.shell),b=await page.locator('.key').first().boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>testGame.hits),1,'real touch hits left drum');await cdp.detach();}
  await page.click('#pause');const before=await page.evaluate(()=>testGame.elapsed);assert.equal(await page.evaluate(()=>testAudio.nodes.size),0,'pause cancels audio nodes');await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>testGame.elapsed),before);await page.click('#resume');await page.locator('.key').first().click();assert.equal(await page.evaluate(()=>testGame.hits),1,'resume countdown cannot accept scored input');await page.waitForFunction(()=>testGame.elapsed>5);await page.evaluate(()=>testAudio.context.suspend());await page.waitForSelector('#pause-dialog[open]');const interrupted=await page.evaluate(()=>testGame.elapsed);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>testGame.elapsed),interrupted);await page.click('#resume');await page.waitForFunction(t=>testGame.elapsed>t+.2,interrupted);console.log(mode+': audio, timed input, hold prevention, pause and audio interruption passed');
  // A complete ordinary wall-clock song, without altering its clock or chart.
  await page.waitForSelector('#result-dialog[open]',{timeout:80000});assert.equal(await page.evaluate(()=>testGame.eligible),true);await page.waitForSelector('#reward .allie-reward a');const count=await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length);assert.equal(count,beforeMode+1);assert.equal(await page.evaluate(()=>testAudio.nodes.size),0);await page.waitForTimeout(300);assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),count);await page.shell.screenshot({path:out+'/'+mode+'-result.png'});await page.click('#back');
  // All ten selections and arrangements complete through real UI handlers using
  // an injected deterministic clock, in addition to the normal run above.
  const ids=await page.locator('.song-card').evaluateAll(b=>b.map(x=>x.dataset.song));for(const id of ids){await page.locator('[data-song="'+id+'"]').click();await page.click('#start');await fastSong(page);assert.equal(await page.evaluate(()=>testGame.hits),await page.evaluate(()=>testGame.notes.length));await page.click('#back');}
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('allie.rhythm.'+document.body.dataset.game+'.v1')).pending.length),0);console.log(mode+': complete real-time song and all ten accelerated song flows awarded one sticker each');
  // Home ends an incomplete run without a claim.
  const initial=await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length);await page.click('#start');await page.shell.click('#allie-home');await page.waitForSelector('#games');assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),initial);
 }
 await page.goto(base+'drums/');await capture(page);await page.click('#start');await page.evaluate(()=>{testAudio.virtual=testAudio.origin+testGame.notes.find(n=>n.time>3&&testGame.notes.filter(x=>x.time===n.time).length===2).time;testAudio.now=()=>testAudio.virtual;});const cdp=await context.newCDPSession(page.shell),drums=await page.locator('.key').all(),boxes=await Promise.all(drums.map(d=>d.boundingBox()));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:boxes.map((b,id)=>({x:b.x+b.width/2,y:b.y+b.height/2,id:id+1}))});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>testGame.hits),2,'two true simultaneous touches hit both drums');await cdp.detach();await page.shell.setViewportSize({width:390,height:844});await page.waitForTimeout(150);await page.shell.setViewportSize({width:844,height:390});await page.waitForSelector('#pause-dialog[open]');console.log('Two simultaneous real touch points work; rotating the screen pauses safely');
 // Finish with no input: no reward, even with a complete timeline.
 await page.click('#quit');await page.click('#start');const claims=await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length);await page.evaluate(()=>{testAudio.virtual=testAudio.origin+testGame.track.end+.1;testAudio.now=()=>testAudio.virtual;});await page.waitForSelector('#result-dialog[open]');assert.equal(await page.evaluate(()=>testGame.eligible),false);assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),claims);assert.equal(await page.locator('#reward a').count(),0);await page.click('#back');
 // A transient failed award remains recoverable across reload and stays idempotent.
 await page.evaluate(()=>{window.realReward=Allie.reward;Allie.reward=async()=>{throw Error('simulated save failure');};});await page.click('#start');await page.evaluate(async()=>{const a=testAudio,g=testGame;a.virtual=a.origin+3;a.now=()=>a.virtual;document.querySelector('.key').click();a.virtual=a.origin+g.track.end+.1;await new Promise(requestAnimationFrame);});await page.waitForSelector('#reward button');const pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('allie.rhythm.drums.v1')).pending[0]);assert.ok(pending);await page.reload();await page.click('#recoveries button');await page.waitForSelector('#recoveries .allie-reward a');assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),claims+1);await page.evaluate(async p=>{await Allie.reward(p.id,'drums');await Allie.reward(p.id,'drums');},pending);assert.equal(await page.evaluate(async()=>Object.keys((await Allie.getState()).claims).length),claims+1);console.log('Empty runs and early Home do not award; failed awards recover once after reload');
 // Shared Use really enters Studio; place one earned unit, Undo refunds it.
 await page.locator('#recoveries .allie-reward a').first().click();await page.waitForFunction(()=>document.body.dataset.tool==='sticker'&&!document.querySelector('#tools button').disabled);const unitsBefore=await page.evaluate(async()=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0));const paper=await page.locator('#layer-bottom').boundingBox();await page.shell.mouse.click(paper.x+paper.width/2,paper.y+paper.height/2);await page.waitForFunction(async n=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0)===n-1,unitsBefore);await page.click('#undo');await page.waitForFunction(async n=>Object.values(Allie.counts(await Allie.getState())).reduce((a,b)=>a+b,0)===n,unitsBefore);console.log('Music sticker Use, actual Studio placement and Undo preserve shared unit rules');
 assert.deepEqual(errors,[]);await browser.close();console.log('Rhythm browser acceptance PASS');
})().catch(e=>{console.error(e);process.exit(1);});
